branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update Chart.yaml version with the new release version (remove 'v' prefix)
        version_without_v=$(echo "${nextRelease.version}" | sed 's/^v//')
        sed -i "s/^version:.*/version: $version_without_v/" Chart.yaml
        
        # Update helmfile.yaml version (keep 'v' prefix)
        sed -i "s/^    version:.*/    version: ${nextRelease.version}/" helmfile.yaml
  - - "@semantic-release/git"
    - assets:
        - "Chart.yaml"
        - "helmfile.yaml"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
preset: "conventionalcommits"
tagFormat: "v${version}"