apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: authentication
type: Opaque
data:
  GITHUB_CLIENT_ID: {{ .Values.auth.github_client_id | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.auth.github_client_secret | b64enc }}
  GITHUB_CALLBACK_URL: {{ .Values.auth.github_callback_url | b64enc }}
  JWT_SECRET: {{ .Values.jwt_secret | b64enc }}