apiVersion: v1
kind: Secret
metadata:
  name: auth-github-apps
  labels:
    app.kubernetes.io/component: authentication
type: Opaque
stringData:
  github-apps.yaml: |
    github_applications:
{{ .Values.github_applications | toYaml | indent 6 }}