apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: authentication
data:
  GITHUB_ORG_NAME: {{ .Values.github_org_name}}
  WEBSITE_URL: {{ .Values.website_url }}
  ALLOWED_ORIGINS: {{ .Values.website_url }}