apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: client
      protocol: TCP
      name: client
    - port: 8222
      targetPort: monitoring
      protocol: TCP
      name: monitoring
    - port: 6222
      targetPort: cluster
      protocol: TCP
      name: cluster
  selector:
    app.kubernetes.io/component: messaging
