apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app.kubernetes.io/component: messaging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: messaging
  template:
    metadata:
      labels:
        app.kubernetes.io/component: messaging
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: monitoring
              containerPort: 8222
              protocol: TCP
            - name: cluster
              containerPort: 6222
              protocol: TCP
          resources:
            {{- toYaml .Values.nats.resources | nindent 12 }}
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats
      volumes:
        - name: nats-config
          configMap:
            name: nats-config