apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
type: Opaque
data:
  postgres-user: {{ .Values.postgres.auth.username | default "postgres" | b64enc }}
  postgres-password: {{ .Values.postgres.auth.password | b64enc }}