apiVersion: v1
kind: Secret
metadata:
  name: registry
  labels:
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}