apiVersion: v1
kind: ConfigMap
metadata:
  name: wss-config
  labels:
    app.kubernetes.io/component: websocket-server
data:
  VM_USER: {{ .Values.wss.vm_user }}
  ALLOWED_ORIGINS: {{ .Values.website_url }}