{{- $urls := list -}}
{{- range $key, $value := .Values.github_applications -}}
  {{- $parsed := urlParse $value.website_url -}}
  {{- $urls = append $urls (printf "%s://%s" $parsed.scheme $parsed.host) -}}
{{- end -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: wss-config
  labels:
    app.kubernetes.io/component: websocket-server
data:
  VM_USER: {{ .Values.wss.vm_user }}
  ALLOWED_ORIGINS: "{{ join "," $urls }}"