apiVersion: v1
kind: ConfigMap
metadata:
  name: wss-config
  labels:
    app.kubernetes.io/component: websocket-server
data:
  NATS_URL: {{ .Values.wss.nats_url }}
  VM_USER: {{ .Values.wss.vm_user }}
  ALLOWED_ORIGINS: {{ .Values.wss.allowed_origins }}
