apiVersion: v1
kind: Service
metadata:
  name: wss
  labels:
    app.kubernetes.io/component: websocket-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/component: websocket-server
