apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app.kubernetes.io/component: www
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/component: www
